### PR TITLE
Fix wrong namespace when requesting chart info

### LINKED ISSUE #2075: Chart new version indicator when select all namespaces
Hello

Would be nice to see the indicator icon when new chart version will appear when clicking on "All namespaces"
Currently the indicator is been shown if you select specific namespace

Selection_008

### PR DESCRIPTION
**Pull request by andresmgot**
### Description of the change

Fix an issue causing the request for the chart to use the current namespace (`_all` if all namespaces is selected) rather than the app namespace.

Apart from that, I found a small bug that two releases in different namespaces were using the same `key` in the list.

### Applicable issues

  - fixes #2075

### CODE REVIEW

File: dashboard/src/actions/apps.ts [hunk 1]
```diff
@@ -244,7 +244,7 @@ export function fetchAppsWithUpdateInfo(
       dispatch(
         getAppUpdateInfo(
           cluster,
-          namespace,
+          app.namespace,
```
Comment (absoludity) [inline dashboard/src/actions/apps.ts:247]: A couple of things confuse the code here, imo:


* the `all` function argument is actually `allStatuses` not all apps across namespaces - can we rename it to be explicit (it's always passed as true from the only call-site afaict, so we could even get rid of it).
* the `fetchApps` and subsequent `App.listApps` have functionality to support fetching apps across all namespaces which is the cause of this change, but it'd be a lot easier to reason about this code if it was obvious why `namespace` can't be used here (because it could have the value `_all`. Perhaps a comment, or renaming it `namespace_or_all` or something.

**Review by absoludity — APPROVED** [review]

File: dashboard/src/actions/apps.ts (hunk 1 above)
Comment (andresmgot) [reply dashboard/src/actions/apps.ts:247]: > * the `all` function argument is actually `allStatuses` not all apps across namespaces - can we rename it to be explicit (it's always passed as true from the only call-site afaict, so we could even get rid of it).

Yes, since we have deleted the code for the Hex UI we can delete it.

> * the `fetchApps` and subsequent `App.listApps` have functionality to support fetching apps across all namespaces which is the cause of this change, but it'd be a lot easier to reason about this code if it was obvious why `namespace` can't be used here (because it could have the value `_all`. Perhaps a comment, or renaming it `namespace_or_all` or something.

:+1:
