### PR TITLE
App repository update form fix for filters (#3447)

### LINKED ISSUE #3447: front: edition of an apprepository filter clears it
### Description:

When creating a new Application Repository, all works as expected. But when editing it to filter out some charts, there is no error on the UI but the resulting `apprepositories` filter is reset:
```
  filterRule:
    jq: ""
```

### Steps to reproduce the issue:

1. Create an App Repository, e.g. [Bitnami](https://charts.bitnami.com/bitnami)
2. Once the App Repository is creted, edit it to modify the filter, eg `nginx, jenkins`
3. Check the resulting `apprepositories`, the filter will be blank even if one was set up at the time of creation

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        5               2021-09-08 10:10:27.536393583 +0000 UTC deployed        kubeapps-7.4.0  2.4.0
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-3+e5758f73ed2a04", GitCommit:"e5758f73ed2a04898a6bba130459e17b95402dcd", GitTreeState:"clean", BuildDate:"2021-08-12T15:05:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-3+e5758f73ed2a04", GitCommit:"e5758f73ed2a04898a6bba130459e17b95402dcd", GitTreeState:"clean", BuildDate:"2021-08-12T15:00:31Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by castelblanque**
Signed-off-by: Rafa Castelblanque <rcastelblanq@vmware.com>

### Description of the change

This PR fixes a problem with updating an app repository with filters.
Repo filter data is now processed correctly both in backend and frontend.

### Benefits

App repository filters are no longer gone after repo data update.

### Possible drawbacks

N/A

### Applicable issues

- fixes #3447

### Additional information

I have added a test file for `AppRepository` given that none was existing.

### CODE REVIEW

File: dashboard/src/shared/AppRepository.ts [hunk 1]
```diff
@@ -59,7 +59,7 @@ export class AppRepository {
           ociRepositories,
           tlsInsecureSkipVerify: skipTLS,
           passCredentials: passCredentials,
-          filter,
+          filterRule: filter,
```
Comment (antgamdia) [inline dashboard/src/shared/AppRepository.ts:62]: I wish every bug was that simple to solve :P

**Review by antgamdia — APPROVED** [review]
Awesome! Thanks, especially for the test. Since we plan to refactor this AppRepo thing at some point, I guess this test was missed or covered in another place, I don't know.
Anyway, great to have it !
