### PR TITLE
Avoid HTTP error codes when running validation

### LINKED ISSUE #1699: Introducing wrong credentials when creating a App Repository cause a logout
### Description:

Details at https://github.com/kubeapps/kubeapps/pull/1692

We should return a 200 and send a JSON response when validating a repo.

### PR DESCRIPTION
**Pull request by andresmgot**
### Description of the change

Avoid just forwarding the response when running the App Repository validation.

Details at #1692

### Applicable issues

  - fixes #1699

### CODE REVIEW

File: pkg/http-handler/http-handler.go [hunk 1]
```diff
@@ -111,22 +110,12 @@ func UpdateAppRepository(handler kube.AuthHandler) func(w http.ResponseWriter, r
...
-		res, err := handler.AsUser(token).ValidateAppRepository(req.Body, mux.Vars(req)["namespace"])
+		err := handler.AsUser(token).ValidateAppRepository(req.Body, mux.Vars(req)["namespace"])
 		if err != nil {
-			returnK8sError(err, w)
-			return
-		}
-		body, err := ioutil.ReadAll(res.Body)
-		if err != nil {
-			returnK8sError(err, w)
+			w.Write([]byte(err.Error()))
```
Comment (absoludity) [inline pkg/http-handler/http-handler.go:115]: Wouldn't this mean that we're now parsing the response body and string matching to determine an error?

File: pkg/http-handler/http-handler_test.go [hunk 2]
```diff
@@ -253,15 +254,18 @@ func TestValidateAppRepository(t *testing.T) {
...
 			name:         "it should return OK if no error is detected",
 			expectedCode: 200,
+			expectedBody: "OK",
 		},
 		{
 			name:         "it should return the error code if given",
 			err:          fmt.Errorf("Boom"),
-			expectedCode: 500,
+			expectedCode: 200,
+			expectedBody: "Boom",
```
Comment (absoludity) [inline pkg/http-handler/http-handler_test.go:268]: Right, this no longer returns the error code. Sorry if it wasn't clear on the previous MP, but what I'd expect here is that *our* API call returns a 200 (as you've done), because it has done its job successfully, but the response data should contain the result of the validation. So here I'd expect that the (json) response include both the status code of the external request, as well as the error message (which you've included as the body).

So a successful validation returns a 200 with a body:
```
{
  valid: true
}
```

and for a validation that didn't succeed:
```
{
  valid: false,
  error: {
    code: 500,
    message: "Boom"
  }
}
```

or something similar. Yes, it works if we depend on the body text being the exact string "OK", but it limits what info we can give the user (ie. with the current change, a blank response from the external URL would give no info, whereas including both the externally received status code with the message will be clearer). But even without that, I'd be keen to avoid an API which requires the client to parse a string response to choose how to handle it.

Comment (andresmgot) [reply pkg/http-handler/http-handler_test.go:268]: it's true that we are missing information without the status code

File: dashboard/src/actions/repos.test.tsx [hunk 3]
```diff
@@ -735,7 +737,7 @@ describe("validateRepo", () => {
 
   it("dispatches checkRepo and errorRepos when the validation cannot be parsed", async () => {
     AppRepository.validate = jest.fn(() => {
-      return { statusCode: 409 };
+      return { error: "forbidden" };
```
Comment (absoludity) [inline dashboard/src/actions/repos.test.tsx:740]: Shouldn't this be returning a `{ code: 409, message: "forbidden" }`? EDIT: Ah, the point is that the error is the same one in that is stringified in the payload below, was just confused by the unexpected data.

File: pkg/kube/kube_handler.go [hunk 4]
```diff
@@ -380,14 +387,26 @@ func getValidationCliAndReq(appRepoBody io.ReadCloser, requestNamespace, kubeapp
...
-func (a *userHandler) ValidateAppRepository(appRepoBody io.ReadCloser, requestNamespace string) (*http.Response, error) {
+func doValidationRequest(cli HTTPClient, req *http.Request) (ValidationResponse, error) {
+	res, err := cli.Do(req)
+	if err != nil {
+		// If the request fail, it's not an internal error
+		return ValidationResponse{Code: 400, Message: err.Error()}, nil
+	}
+	body, err := ioutil.ReadAll(res.Body)
+	if err != nil {
+		return ValidationResponse{}, fmt.Errorf("Unable to parse validation response. Got: %v", err)
```
Comment (absoludity) [inline pkg/kube/kube_handler.go:398]: If you use a pointer type for the returned `*ValidationResponse` this can just be nil? (and below)

File: dashboard/src/actions/repos.test.tsx (hunk 3 above)
Comment (andresmgot) [reply dashboard/src/actions/repos.test.tsx:740]: right, I keep setting dummy data in the tests but it's true that it's more readable with a real result.
