### PR TITLE
fix upgrade for charts where the optional app version not specified

### LINKED ISSUE #3253: Unable to upgrade Helm release for chart without appVersion
### Description:
I've successfully installed a Helm release from a chart stored on an OCI repository, however I'm not able to upgrade it from Kubeapps. I've also tested to store the chart on a Chartmuseum repository and the upgrade fails in the same way.
When clicking on upgrade, the page starts loading and then hangs, the loading wheel is spinning forever:
kubeapps_keeps_spinning

When looking at the browser console and the network requests, I don't notice any failure. The page just stops issuing requests at some point. Looking at the Kubeapps logs doesn't show any error: [kubeapps_logs.txt.gz](https://github.com/kubeapps/kubeapps/files/6963341/kubeapps_logs.txt.gz)

Upgrading the Helm release from the command line works fine.
Upgrading a release steming from another chart, Kubeapps which comes from the Bitnami repository, works fine from Kubeapps.

### Steps to reproduce the issue:

1. Set up a local OCI or Chartmuseum repository
2. Upload the `etcd-debug` chart attached: [etcd-debug.tar.gz](https://github.com/kubeapps/kubeapps/files/6963383/etcd-debug.tar.gz)
3. Install a new release from Kubeapps
4. Upgrade it from Kubeapps

### Additional information you deem important:

The following trivial chart didn't experience the issue: [trivial.tar.gz](https://github.com/kubeapps/kubeapps/files/6963389/trivial.tar.gz)

so it doesn't seem to be related to the repository type.

### Version of Helm, Kubeapps and Kubernetes:

 I'm been facing the issue on the latest version of Kubeapps:
* App Version: 2.3.3
* Chart Version: 7.1.8

I have also tested a previous version but it didn't help:
* App Version: 2.2.1
* Chart Version: 5.3.4

I'm using microk8s v1.21.3.

Output of `microk8s.helm3 version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `microk8s.helm3 list -n <kubeapps-namespace> <kubeapps-release-name>`:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        27              2021-08-06 09:14:32.276950409 +0000 UTC deployed        kubeapps-7.1.8  2.3.3
```

- Output of `microk8s.kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-3+90fd5f3d2aea0a", GitCommit:"90fd5f3d2aea0a5788b15a6f0a05e70381af7787", GitTreeState:"clean", BuildDate:"2021-07-16T22:06:06Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-3+90fd5f3d2aea0a", GitCommit:"90fd5f3d2aea0a5788b15a6f0a05e70381af7787", GitTreeState:"clean", BuildDate:"2021-07-16T22:01:05Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by dlaloue-vmware**
### Description of the change

The change is to fix upgrade of apps when the charts does not provide an app version (optional field).
One change is to ensure that "undefined" is not sent as a filter value when querying the list of matching charts.
The other change is to remove the app version as a condition to render the AppUpgrade component.

### Benefits

Upgrade of apps with charts with no app version is now possible.

### Possible drawbacks

none

### Applicable issues

- fixes  #3253

### Additional information

This is the simplest change. The UI will most likely change once the new APIs are integrated.

### CODE REVIEW

File: dashboard/src/actions/apps.ts [hunk 1]
```diff
@@ -172,8 +172,7 @@ export function getAppWithUpdateInfo(
         app.chart &&
         app.chart.metadata &&
         app.chart.metadata.name &&
-        app.chart.metadata.version &&
-        app.chart.metadata.appVersion
+        app.chart.metadata.version
```
Comment (antgamdia) [inline dashboard/src/actions/apps.ts:175]: It can be simplified using the `?.`  operator, I think (but fine as is)

```js
if(
 app?.chart?.metadata?.name &&
 app?.chart?.metadata?.version &&
 app?.chart?.metadata?.appVersion
){
...
```

**Review by antgamdia — APPROVED** [review]
Awesome, thanks for the fix!!

File: dashboard/src/actions/apps.ts (hunk 1 above)
Comment (dlaloue-vmware) [reply dashboard/src/actions/apps.ts:175]: yes, that is a shorter way to write the condition. but here i was looking at only making changes for the bug fixes, refactoring was not really necessary.

for the other file, ?? is what i was looking for and is so much nicer to use (next time :-))
