### PR TITLE
ChartView: Skip comments and render hash links

### LINKED ISSUE #1390: Markup is not rendered correctly issues with comments and links
### Description:

We have two render issues with the README.md Markdown in kubeapps:
- ```<!-- -->``` will be rendered as plain text in kubeapps
- Relative Links break inside kubeapps
  -  There was already a issue open for the links but its not solved: https://github.com/kubeapps/kubeapps/pull/709 (not sure though what this solved in detail, just wanted to mention it)

### Steps to reproduce the issue:

Create README.md which contains:

```

<!--ts-->
   * [Chart Details](#chart-details)
<!--te-->


# Chart Details
```

### Describe the results you received:

Rendered output:
```
<!--ts-->
   * [Chart Details](#chart-details)
<!--te-->


# Chart Details
```
and link #chart-details is broken.

### Describe the results you expected:

Rendered output:
```
   * [Chart Details](#chart-details)

# Chart Details
```
and link #chart-details works.

### Version of Helm, Kubeapps and Kubernetes:
v1.7.2

### PR DESCRIPTION
**Pull request by andresmgot**
### Description of the change

Ignore comments and fix hash links in the ChartView.

Apparently React-Router doesn't play well with hash links so I had to add a new dependency:
https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604

Tested with the ChartMuseum chart. This is before the change:

Screencast2020-01-22172036

And this is with this fix, the comment is removed and the link works:

Screencast2020-01-22171757

### Applicable issues

  - fixes #1390

### CODE REVIEW

File: dashboard/src/components/ChartView/LinkRenderer.tsx [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import * as React from "react";
+import { HashLink as Link } from "react-router-hash-link";
+
+const LinkRenderer: React.SFC<{}> = (props: any) => {
+  if (props.href.startsWith("#")) {
+    return <Link to={props.href}>{props.children}</Link>;
+  }
+  return <a href={props.href}>{props.children}</a>;
```
Comment (absoludity) [inline dashboard/src/components/ChartView/LinkRenderer.tsx]: Why don't we use the normal `Link` here from `react-router-dom` that we use elsewhere? Ah, because this `LinkRenderer` is only being used for rendering the README, so it will never contain internal application links - got it. Not sure if it's worth a comment, up to you.
