### PR TITLE
Delete cronjob related to namespaced repos

### LINKED ISSUE #1832: Deleting a namespaced app repo does not delete cronjob nor assets
### Description:

Deleting a namespaced app repo leaves the sync cronjob in place and so assets are still returned (but unable to be deployed) after deletion.

### Steps to reproduce the issue:

1. Install `my-repo` in the default namespace using `https://charts.bitnami.com/bitnami`
2. Verify the cronjob is installed, sync performed, and results appear in the catalog
3. Delete the `my-repo` repo in the default namespace

### Describe the results you received:

Results are still shown for the my-repo repository in the catalog, but cannot be deployed.
The cronjob is still present in the kubeapps namespace for syncing the data.

### Describe the results you expected:

Results should no longer appear, nor should the sync cronjob still be present.

### Version of Helm, Kubeapps and Kubernetes:
- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}```
```
- Output of `helm list <kubeapps-release-name>`:

```
helm list -n kubeapps
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                 APP VERSION
chartmuseum     kubeapps        1               2020-06-24 16:18:45.924973082 +1000 AEST        deployed        chartmuseum-2.13.0    0.12.0     
kubeapps        kubeapps        1               2020-06-24 15:57:01.541583472 +1000 AEST        deployed        kubeapps-3.7.2        v1.10.2    
```

BUT note running a development dashboard image.

- Output of `kubectl version`:

```
k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

### PR DESCRIPTION
**Pull request by andresmgot**
### Description of the change

As explained at #1832, for namespaced repos, the cronjob used to sync it was not being deleted after deleting the apprepo.

I also found that the cleanup job for the database was not being created, more details inline.

### Applicable issues

  - fixes #1832

### Additional information

The main method of the controller `syncHandler` is not being tested, and because of its length and complexity I don't have the time to create those tests now so I just tested this fix IRL.

### CODE REVIEW

File: cmd/apprepository-controller/controller.go [hunk 1]
```diff
@@ -273,14 +273,26 @@ func (c *Controller) syncHandler(key string) error {
 		if errors.IsNotFound(err) {
 			log.Infof("AppRepository '%s' no longer exists so performing cleanup of charts from the DB", key)
 			// Trigger a Job to perfrom the cleanup of the charts in the DB corresponding to deleted AppRepository
-			_, err = c.kubeclientset.BatchV1().Jobs(namespace).Create(context.TODO(), newCleanupJob(apprepo, c.conf), metav1.CreateOptions{})
```
Comment (andresmgot) [inline cmd/apprepository-controller/controller.go:276]: `apprepo` is `nil` since the line 269 fails to retrieve it. This was causing a panic in the controller. We just need the namespace and the name at this point.

Comment (antgamdia) [reply cmd/apprepository-controller/controller.go:276]: Good catch!  Thank you for pointing this out!

File: cmd/apprepository-controller/controller.go [hunk 2]
```diff
@@ -273,14 +273,26 @@ func (c *Controller) syncHandler(key string) error {
...
+			_, err = c.kubeclientset.BatchV1().Jobs(c.conf.KubeappsNamespace).Create(context.TODO(), newCleanupJob(c.conf.KubeappsNamespace, namespace, name, c.conf), metav1.CreateOptions{})
+			if err != nil {
+				log.Errorf("Unable to create cleanup job: %v", err)
+				return err
+			}
+
+			// TODO: Workaround until the sync jobs are moved to the repoNamespace (#1647)
+			// Delete the cronjobo in the Kubeapps namespace to avoid re-syncing the repository
```
Comment (antgamdia) [inline cmd/apprepository-controller/controller.go:283]: Very minor typo here (`cronjobo`)

**Review by antgamdia — APPROVED** [review]
