### PR TITLE
Fix repeated operator resources shown in dashboard (#3574)

### LINKED ISSUE #3574: Dashboard shows multiple application for single operator
### Description:

I see multiple copies of the installed operator(s) in the application list:
image

### Steps to reproduce the issue:

1. install operator (I scale kiali, but the same was with cert-manager)
2. Not sure - apply several changes of CR (`kubectl apply -n istio-system -f kiali-install.yaml`)
3. Go to applications (any NS)
4. select "Show apps in all namespaces"

### Describe the results you received:

See multiple copies of plate "A configuration file for a Kiali installation."

### Describe the results you expected:

See only one plate per installed operator (or per CR instance of CRD?)

### Additional information you deem important (e.g. issue happens only occasionally):

N/A

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `helm list -n istio-system`:

```
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

### PR DESCRIPTION
**Pull request by castelblanque**
Signed-off-by: Rafa Castelblanque <rcastelblanq@vmware.com>

### Description of the change

Fix for operators resources showing repeated times (as many as namespaces existing in cluster) when listing installed items with "Show apps in all namespaces" marked in Dashboard.
Also added the label with namespace to cards.

Issue affects only the Dashboard/FE.

### Benefits

Realistic view of what operators resources are installed on each namespace.

### Possible drawbacks

N/A

### Applicable issues

- fixes #3574

### CODE REVIEW

File: dashboard/src/actions/operators.ts [hunk 1]
```diff
@@ -321,7 +321,7 @@ export function getResources(
         try {
           const csvResources = await Operators.listResources(
             cluster,
-            namespace,
+            csv.metadata.namespace,
```
Comment (antgamdia) [inline dashboard/src/actions/operators.ts:324]: So this is why the namespace wasn't being set? Interesting

**Review by antgamdia — APPROVED** [review]
Great! Thanks, also, for the explanation in https://github.com/kubeapps/kubeapps/issues/3574#issuecomment-995048538

File: dashboard/src/actions/operators.ts (hunk 1 above)
Comment (castelblanque) [reply dashboard/src/actions/operators.ts:324]: Exactly, when having selected "all namespaces" in the switch button, `namespace` value would be `""`.
