### PR TITLE
Fix a null pointer in fetchNamespaces

### LINKED ISSUE #2956: An error occurred: Cannot read property 'map' of undefined.
### Description:

when I login to the kubeapps use kubernetes sa secrets， the error like this: 

image

I dont know what happend and how to fix this.

### Steps to reproduce the issue:

install step on this: 

 https://kubeapps.com/docs/getting-started/

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
# helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
# helm list -n kubeapps
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-06-08 15:45:50.840028641 +0800 CST	deployed	kubeapps-6.1.2	2.3.2
```

- Output of `kubectl version`:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

We had an unhandled null in the `fetchNamespaces` action; this PR simply adds a check to display the proper error message back to the user

### Benefits

No more "cannot read property .map from undefined"  ugly errors : )

### Possible drawbacks

N/A

### Applicable issues

  - fixes #2956

### Additional information

N/A

### CODE REVIEW

File: dashboard/src/actions/namespace.ts [hunk 1]
```diff
@@ -55,7 +55,11 @@ export function fetchNamespaces(
   return async dispatch => {
     try {
       const namespaceList = await Namespace.list(cluster);
-      const namespaceStrings = namespaceList.namespaces.map((n: IResource) => n.metadata.name);
+
+      const namespaceStrings =
+        namespaceList.namespaces === undefined
+          ? []
+          : namespaceList.namespaces.map((n: IResource) => n.metadata.name);
```
Comment (absoludity) [inline dashboard/src/actions/namespace.ts:62]: Did we stop using lodash.get? This would be simpler as something like `get(namespaceList, "namespaces", []).map(...)` ?

**Review by absoludity — APPROVED** [review]

File: dashboard/src/actions/namespace.ts (hunk 1 above)
Comment (antgamdia) [reply dashboard/src/actions/namespace.ts:62]: Ooops, yep, we still use it... but Lodash is not the first thing coming to my mind. Thanks for the suggestion!
