### PR TITLE
parameterize VersionsInSummary - complete fix

### LINKED ISSUE #3588: Some Chart versions hidden from dropdown when deploying an application
### Description:

We’re running into a very strange bug and need help since it’s affecting customers of our infrastructure product.

We use Kubeapps for customers to deploy applications, and we use Chartmuseum to store charts for them to use. However, when we want to select a version of an application to deploy, some versions are hidden.

I’ve done some testing, and all the versions we offer are indeed available in chartmuseum, they show up when we GET on /api/charts/chart-name, and they can be pulled using “helm pull” to get the tar bundle. However it seems that Kubeapps is failing to show all these versions in the dropdown. For example, we start off by seeing the versions 1.19.4, 1.19.5, and 1.19.6:

Screen Shot 2021-10-13 at 11 08 31 AM

but when a test chart like 1.19.7-CCT-XXXX (a test chart created for testing changes introduced by a ticket) is uploaded, some versions start disappearing.

Screen Shot 2021-10-13 at 11 13 14 AM

However, I know for sure that Kubeapps knows about these hidden versions, since older applications deployed using these versions can still be accessed:

Screen Shot 2021-10-13 at 11 13 34 AM

as opposed to showing us an error about the chart version not existing:

Screen Shot 2021-10-13 at 11 31 07 AM

This leads me to believe that the dropdown is bugged in some way. We just started running into this issue, and it seems (not 100% sure on this) to start occurring when test charts (X.X.X-ABC-XXXX) are uploaded. Please tell us if you know anything about why this is happening. thank you for the help

Slack message: https://kubernetes.slack.com/archives/C9D3TSUG4/p1634139332089700

Our version history:
oct 6: we updated kubeapps chart to 7.5.4, app version 2.4.0
sept 9: we updated kubeapps chart to 7.4.0, app version 2..4.0
july 7, we updated kubeapps chart to 7.1.2, app version 2.3.2

### Steps to reproduce the issue:

1. Deploy chartmuseum and kubeapps
2. configure chartmuseum as an app repository for kubeapps
3. upload charts to chartmuseum
4. refresh the app repository on kubeapps ui, or by running the sync cronjob

### Describe the results you received:

Some chart versions don't show in the dropdown

### Describe the results you expected:

All chart versions show up in the dropdown

### Additional information you deem important (e.g. issue happens only occasionally):

We use particular version names when deploying test charts (chart which include changes related to a ticket). These charts have the format X.X.X-TICKET. This might be unexpected and might be partially causing the issue. but we've been doing this for years without running into this issue before.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
# nothing, we don't deploy kubeapps through helm install, but through argocd
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by satya-dillikar**
### Description of the change

Users can now control the “Package Version” shown in the UX via values.yaml file. By default, versionSummary is set as { major: 3, minor: 3, patch: 3 }. But users can customize these values as per their needs.

The configured values are passed to the helm plugin via kubeapps-apis server --plugin-config-path param.

### Benefits

 This new parameter VersionsInSummary can be populated from the values.yaml file of the helm chart.

### Possible drawbacks

None
### Applicable issues

- fixes #3588 

Users can now control the “Package Version” shown in the UX via values.yaml file. By default, versionSummary is set as { major: 3, minor: 3, patch: 3 }. But users can customize these values as per their needs.

### Additional information

More proper fix is still pending.

### CODE REVIEW

File: cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go [hunk 1]
```diff
@@ -1371,9 +1372,10 @@ func TestGetAvailablePackageVersions(t *testing.T) {
 
 func TestPackageAppVersionsSummary(t *testing.T) {
 	testCases := []struct {
-		name            string
-		chart_versions  []models.ChartVersion
-		version_summary []*corev1.PackageAppVersion
+		name                    string
+		chart_versions          []models.ChartVersion
+		version_summary         []*corev1.PackageAppVersion
+		exp_versions_in_summary VersionsInSummary
```
Comment (absoludity) [inline cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go:1378]: Just wondering what the "exp_" is for here? This one isn't an expected value, but rather an input value? The expected value is the resulting version summary? Fine either way, just confused me reading it.

**Review by absoludity — APPROVED** [review]
Looks good, thanks Satya. You might want to update the "Fixes xxxx." in the PR description to instead just reference the issue (ie. "Ref: xxxx"), otherwise landing this PR will close the issue as fixed.

**Review by absoludity — APPROVED** [review]
Excellent focused change @satya-dillikar , well done!

Two small things worth mentioning:

1. As per the inline comments, I'm not sure about putting the kubeapps-apis plugins config in the shared config map (it's shared only because the clusters config is re-used across services, whereas the plugins config is specific). Maybe it's fine as is, given it's only mounted if explicitly wanted?
2. Do you think it's worth adding a test function with a couple of test cases for your new `parsePluginConfig` function? If so, you can use some yaml as input, the test converts the yaml to json, writes it to a temporary file (remember to delete afterwards in your `defer`, see [an example](https://pkg.go.dev/os@go1.17.2#example-CreateTemp)), then calls the function with the filename to verify the expected result.
3. We need to update the version in the Chart.yaml. In your branch it's currently set to [`7.5.12-dev1` in the Chart.yaml](https://github.com/satya-dillikar/kubeapps/blob/versionInSummary_part1/chart/kubeapps/Chart.yaml#L36), so just update that to `7.5.12-dev2` please. 

Note, the e2e test had spuriously failed. I re-ran it and it passed.

Let me know what you think, feel free to land it when you've updated the chart version, depending whether you also add the tests.

File: chart/kubeapps/templates/shared/config.yaml [hunk 2]
```diff
@@ -14,4 +14,6 @@ metadata:
 data:
   clusters.conf: |-
 {{ .Values.clusters | toPrettyJson | indent 4 }}
+  plugins.conf: |-
+{{ .Values.kubeappsapis.pluginConfig | toPrettyJson | indent 4 }}
```
[the remark this answers is not in the document]
Comment (satya-dillikar) [reply chart/kubeapps/templates/shared/config.yaml]: I have created a new configmap for kubeappsapis

File: cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go [hunk 3]
```diff
@@ -77,11 +85,53 @@ type Server struct {
...
+				} `json:"v1alpha1"`
+			} `json:"packages"`
+		} `json:"core"`
+		Helm struct {
+			Packages struct {
+				V1alpha1 struct {
+					SomeConfigOption string `json:"someConfigOption"`
+				} `json:"v1alpha1"`
+			} `json:"packages"`
+		} `json:"helm"`
```
[the remark this answers is not in the document]
Comment (satya-dillikar) [reply cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go]: I have removed this.

File: cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go [hunk 4]
```diff
@@ -77,11 +85,53 @@ type Server struct {
 	manager                  utils.AssetManager
 	actionConfigGetter       helmActionConfigGetter
 	chartClientFactory       chartutils.ChartClientFactoryInterface
+	versionsInSummary        VersionsInSummary
+}
+
+func parsePluginConfig(pluginConfigPath string) VersionsInSummary {
```
[the remark this answers is not in the document]
Comment (satya-dillikar) [reply cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go:92]: I shall keep as-is for now. But updated comments in the code.

[the remark this answers is not in the document]
Comment (satya-dillikar) [reply cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go:92]: Please review the new set of changes in my new commit on Nov3 
[ "add new TC & configmap" ](https://github.com/kubeapps/kubeapps/pull/3703/commits/76cae8c76d9d6c16c26d21a056656cef1dd2bf94)


I had some merge issues, hence you will see more commits. Please ignore those.
Thanks again.

**Comment by satya-dillikar** [comment]
> Excellent focused change @satya-dillikar , well done!
> 
> Two small things worth mentioning:
> 
> 1. As per the inline comments, I'm not sure about putting the kubeapps-apis plugins config in the shared config map (it's shared only because the clusters config is re-used across services, whereas the plugins config is specific). Maybe it's fine as is, given it's only mounted if explicitly wanted?
> 2. Do you think it's worth adding a test function with a couple of test cases for your new `parsePluginConfig` function? If so, you can use some yaml as input, the test converts the yaml to json, writes it to a temporary file (remember to delete afterwards in your `defer`, see [an example](https://pkg.go.dev/os@go1.17.2#example-CreateTemp)), then calls the function with the filename to verify the expected result.
> 3. We need to update the version in the Chart.yaml. In your branch it's currently set to [`7.5.12-dev1` in the Chart.yaml](https://github.com/satya-dillikar/kubeapps/blob/versionInSummary_part1/chart/kubeapps/Chart.yaml#L36), so just update that to `7.5.12-dev2` please.
> 
> Note, the e2e test had spuriously failed. I re-ran it and it passed.
> 
> Let me know what you think, feel free to land it when you've updated the chart version, depending whether you also add the tests.

I have addressed all three points mentioned here in my below commit.

File: chart/kubeapps/templates/kubeappsapis/configmap.yaml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: {{ template "kubeapps.kubeappsapis.fullname" . }}-configmap
+data:
+  plugins.conf: |-
+{{- if .Values.kubeappsapis.pluginConfig }}
+{{ .Values.kubeappsapis.pluginConfig | toPrettyJson | indent 4 }}
+{{- end }}
```
Comment (absoludity) [inline chart/kubeapps/templates/kubeappsapis/configmap.yaml:9]: I wonder if this config map should be conditional, rather than just the value here. Currently it means that if no pluginConfig is specified, we'll have this unused configmap being created with an empty value, whereas if the condition wrapped the whole config map, it'd simply not be created?

File: chart/kubeapps/templates/kubeappsapis/deployment.yaml [hunk 6]
```diff
@@ -145,18 +148,27 @@ spec:
...
+          {{- if .Values.clusters }}
             - name: clusters-config
               mountPath: /config
             - name: ca-certs
               mountPath: /etc/additional-clusters-cafiles
           {{- end }}
-      {{- if .Values.clusters }}
+          {{- if .Values.kubeappsapis.pluginConfig }}
+            - name: plugins-config
+              mountPath: /config/kubeapps-apis
```
Comment (absoludity) [inline chart/kubeapps/templates/kubeappsapis/deployment.yaml:160]: Great, I was wondering whether you could specify a subpath of an existing mount path (`/config`)for the mount path. Glad to know you can.

File: cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go [hunk 7]
```diff
@@ -99,6 +145,9 @@ func NewServer(configGetter server.KubernetesConfigGetter, globalPackagingCluste
 		log.Fatalf("%s", err)
 	}
 
+	versionsInSummary := parsePluginConfig(pluginConfigPath)
+	log.Infof("NewServer: versionsInSummary %v\n", versionsInSummary)
```
Comment (absoludity) [inline cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go:149]: This looks like debugging rather than something we actually want to log at the info level?

File: cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go [hunk 8]
```diff
@@ -1515,20 +1524,243 @@ func TestPackageAppVersionsSummary(t *testing.T) {
...
+func TestParsePluginConfig(t *testing.T) {
+	testCases := []struct {
+		name                    string
+		pluginYAMLConf          string
+		exp_versions_in_summary VersionsInSummary
+	}{
+		{
+			name:                    "empty plugin config",
+			pluginYAMLConf:          ``,
+			exp_versions_in_summary: VersionsInSummary{0, 0, 0},
```
Comment (absoludity) [inline cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go:1713]: Hmm, if the config is empty, shouldn't we return the default (3, 3, 3)?

File: cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go [hunk 9]
```diff
@@ -1515,20 +1524,243 @@ func TestPackageAppVersionsSummary(t *testing.T) {
...
+			}
+			if err := f.Close(); err != nil {
+				log.Fatalf("%s", err)
+			}
+			if got, want := parsePluginConfig(f.Name()), tc.exp_versions_in_summary; !cmp.Equal(want, got, opts) {
+				t.Errorf("mismatch (-want +got):\n%s", cmp.Diff(want, got, opts))
+			}
+		})
+	}
+}
```
Comment (absoludity) [inline cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go:1763]: Great, thanks for the extra  test.

**Review by absoludity — APPROVED** [review]
Thanks for the update. A couple of small thoughts that you can ignore if you want, just see what you think.

Land when ready (do you have permission to merge the PR? otherwise let me know and I'll do it when you're ready).

**Comment by satya-dillikar** [comment]
> Thanks for the update. A couple of small thoughts that you can ignore if you want, just see what you think.
> 
> Land when ready (do you have permission to merge the PR? otherwise let me know and I'll do it when you're ready).

I don't see the option to "merge in this PR". Probably I don't have permission. Please merge or add me with the permissions.

Thanks
