### PR TITLE
Check missing chart repository

### LINKED ISSUE #511: Accessing a chart from a missing repository crashes a chart
When accessing a chart from a missing repository:

screen shot 2018-08-20 at 13 33 43

Found when clicking on the button `Sevice Instances > Install Catalog` after deleting the `svc-cat` repository.

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes: #511

Show a "Not found" error when the chart or the chart repository doesn't exist. It covers the chart view (e.g. `/charts/foo/bar`) and the deployment form (e.g. `apps/ns/default/new/foo/aerospike/versions/0.1.7`) components.

Caveat: This fixes #511 but I think we should refactor the way we handle errors in the views. I think that we can probably move the error checking to an upper lever to avoid having to reimplement the error handling in all the possible views.

screen shot 2018-09-10 at 14 57 05

### CODE REVIEW

File: dashboard/src/actions/charts.ts [hunk 1]
```diff
@@ -57,49 +57,62 @@ const allActions = [
 ].map(getReturnOfExpression);
 export type ChartsAction = typeof allActions[number];
 
+async function httpGet(dispatch: Dispatch<IStoreState>, targetURL: string) {
```
[the remark this answers is not in the document]
Comment (migmartri) [reply dashboard/src/actions/charts.ts]: https://github.com/kubeapps/kubeapps/issues/606

File: dashboard/src/actions/charts.ts [hunk 2]
```diff
@@ -57,49 +57,62 @@ const allActions = [
...
+  try {
+    const response = await fetch(targetURL);
+    const json = await response.json();
+    if (!response.ok) {
+      const error = json.data || response.statusText;
+      if (response.status === 404) {
+        dispatch(errorChart(new MissingChart(error)));
```
Comment (migmartri) [inline dashboard/src/actions/charts.ts]: I have mixed feelings here, I am not sure if doing all this specific code makes sense. I mean, 404 means the same for all kind of resources.

File: dashboard/src/components/AppUpgrade/AppUpgrade.tsx [hunk 3]
```diff
@@ -31,7 +31,7 @@ interface IAppUpgradeProps {
   fetchChartVersions: (id: string) => Promise<{}>;
   getApp: (releaseName: string, namespace: string) => Promise<void>;
   getBindings: () => Promise<IServiceBindingWithSecret[]>;
-  getChartVersion: (id: string, chartVersion: string) => Promise<void>;
+  getChartVersion: (id: string, chartVersion: string) => Promise<{}>;
```
Comment (migmartri) [inline dashboard/src/components/AppUpgrade/AppUpgrade.tsx]: Why is it this change?

File: dashboard/src/actions/charts.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (prydonius) [reply dashboard/src/actions/charts.ts]: We should switch this to axios eventually, but since this is self-contained, I'm okay keeping this for now and throwing it away later with #606.

File: dashboard/src/actions/charts.ts (hunk 2 above)
Comment (prydonius) [reply dashboard/src/actions/charts.ts]: Agreed, we should just raise the NotFoundError here

File: dashboard/src/components/AppUpgrade/AppUpgrade.tsx (hunk 3 above)
Comment (prydonius) [reply dashboard/src/components/AppUpgrade/AppUpgrade.tsx]: we return the response now: https://github.com/kubeapps/kubeapps/pull/604/files#diff-32e6760e59b5e0433a9fae60151e0a8dR108

File: dashboard/src/components/ChartView/ChartView.tsx [hunk 4]
```diff
@@ -138,6 +142,17 @@ class ChartView extends React.Component<IChartViewProps> {
       repoURL === "https://kubernetes-charts-incubator.storage.googleapis.com"
     );
   }
+
+  private renderError(error: Error, action: string = "view") {
+    const { chartID } = this.props;
+    switch (error.constructor) {
+      case MissingChart:
```
Comment (prydonius) [inline dashboard/src/components/ChartView/ChartView.tsx]: we should removing the specific MissingChart error here

File: dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+  error: undefined,
+  selected: {} as IChartState["selected"],
+  deployChart: jest.fn(),
+  push: jest.fn(),
+  fetchChartVersions: jest.fn(),
+  getBindings: jest.fn(),
+  getChartVersion: jest.fn(),
+  getChartValues: jest.fn(),
+  namespace: "default",
+};
```
Comment (prydonius) [inline dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx]: new line after this

File: dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+describe("renders an error", () => {
+  it("renders an error if it cannot find the given chart", () => {
+    const wrapper = shallow(
+      <DeploymentForm
+        {...defaultProps}
+        selected={{ error: new MissingChart() } as IChartState["selected"]}
+      />,
+    );
+    expect(wrapper.find(NotFoundErrorPage).exists()).toBe(true);
+  });
```
Comment (prydonius) [inline dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx]: new lines between these

File: dashboard/src/components/DeploymentForm/DeploymentForm.tsx [hunk 7]
```diff
@@ -207,6 +211,17 @@ class DeploymentForm extends React.Component<IDeploymentFormProps, IDeploymentFo
   public handleValuesChange = (value: string) => {
     this.setState({ appValues: value, valuesModified: true });
   };
+
+  private renderSelectedError(error: Error) {
+    const { chartID } = this.props;
+    switch (error.constructor) {
+      case MissingChart:
```
Comment (prydonius) [inline dashboard/src/components/DeploymentForm/DeploymentForm.tsx]: we should removing the specific MissingChart error here

File: dashboard/src/actions/charts.test.tsx [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+      { type: getType(actions.charts.receiveCharts), charts: response },
+    ];
+    await store.dispatch(actions.charts.fetchCharts("foo"));
+    expect(store.getActions()).toEqual(expectedActions);
+    expect(fetchMock.mock.calls[0][0]).toBe("/api/chartsvc/v1/charts/foo");
+  });
+  it("returns a 404 error", async () => {
+    const expectedActions = [
+      { type: getType(actions.charts.requestCharts) },
+      { type: getType(actions.charts.errorChart), err: new MissingChart("not found") },
```
[the remark this answers is not in the document]
Comment (andresmgot) [reply dashboard/src/actions/charts.test.tsx]: Done, now it's not needed to have that differentiation

File: dashboard/src/actions/charts.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (andresmgot) [reply dashboard/src/actions/charts.ts]: 👍
