### PR TITLE
[Dashboard] Treat anything with items as a list in AppView

### LINKED ISSUE #1025: Unable to install prometheus-operator
kubeapp version: 1.3.0
Kubernetes version: v1.12.5
helm version : v2.11.0
chart : offical/prometheus-operator5.5.1

error message: the server could not find the requested resource
recurrent : 100%

when useing helm cli chart installed fine

**useing kubeapp tiller log:**
```
2019/05/08 08:55:29 info: manifest "prometheus-operator/charts/grafana/templates/dashboards-json-configmap.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/endpoints.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/exporters/kube-dns/servicemonitor.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/exporters/kube-controller-manager/endpoints.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/charts/kube-state-metrics/templates/monitor.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/exporters/kube-scheduler/endpoints.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/exporters/kube-etcd/endpoints.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/prometheus/podDisruptionBudget.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/alertmanager/podDisruptionBudget.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/monitor.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/prometheus/additionalAlertRelabelConfigs.yaml" is empty. Skipping.
2019/05/08 08:55:29 info: manifest "prometheus-operator/templates/grafana/configmap-dashboards.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/templates/prometheus/additionalScrapeConfigs.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/templates/alertmanager/ingress.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/templates/prometheus/servicemonitors.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/templates/exporters/kube-dns/service.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/templates/prometheus/additionalAlertmanagerConfigs.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/05/08 08:55:30 info: manifest "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" is empty. Skipping.
[tiller] 2019/05/08 08:55:30 performing install for
[tiller] 2019/05/08 08:55:30 dry run for zeroed-garfish
[tiller] 2019/05/08 08:55:30 validation skipped because CRD hook is present
[tiller] 2019/05/08 08:55:34 preparing install for five-picture
[storage] 2019/05/08 08:55:34 getting release history for "five-picture"
[tiller] 2019/05/08 08:55:34 rendering prometheus-operator chart using values
```

**useing helm cli tiller logs:**
```
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/alertmanager/podDisruptionBudget.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus/additionalPrometheusRules.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/grafana/configmap-dashboards.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/exporters/kube-dns/servicemonitor.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/exporters/kube-scheduler/endpoints.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus/additionalAlertRelabelConfigs.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/endpoints.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/exporters/kube-etcd/endpoints.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/alertmanager/ingress.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/exporters/kube-controller-manager/endpoints.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/exporters/kube-dns/service.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/charts/prometheus-node-exporter/templates/monitor.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/charts/grafana/templates/dashboards-json-configmap.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus/podDisruptionBudget.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus/additionalScrapeConfigs.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus/servicemonitors.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/charts/kube-state-metrics/templates/monitor.yaml" is empty. Skipping.
2019/05/08 10:10:51 info: manifest "prometheus-operator/templates/prometheus/additionalAlertmanagerConfigs.yaml" is empty. Skipping.
[tiller] 2019/05/08 10:10:51 performing install for
[tiller] 2019/05/08 10:10:51 executing 5 crd-install hooks for fuzzy-marsupial
[tiller] 2019/05/08 10:10:51 deleting crd-install hook alertmanagers.monitoring.coreos.com for release fuzzy-marsupial due to "before-hook-creation" policy
[kube] 2019/05/08 10:10:52 Starting delete for "alertmanagers.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/05/08 10:10:52 customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" not found
[kube] 2019/05/08 10:10:52 building resources from manifest
[kube] 2019/05/08 10:10:52 creating 1 resource(s)
[tiller] 2019/05/08 10:10:52 deleting crd-install hook prometheuses.monitoring.coreos.com for release fuzzy-marsupial due to "before-hook-creation" policy
[kube] 2019/05/08 10:10:52 Starting delete for "prometheuses.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/05/08 10:10:52 customresourcedefinitions.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" not found
[kube] 2019/05/08 10:10:52 building resources from manifest
[kube] 2019/05/08 10:10:52 creating 1 resource(s)
[tiller] 2019/05/08 10:10:52 deleting crd-install hook prometheusrules.monitoring.coreos.com for release fuzzy-marsupial due to "before-hook-creation" policy
[kube] 2019/05/08 10:10:52 Starting delete for "prometheusrules.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/05/08 10:10:52 customresourcedefinitions.apiextensions.k8s.io "prometheusrules.monitoring.coreos.com" not found
[kube] 2019/05/08 10:10:52 building resources from manifest
[kube] 2019/05/08 10:10:52 creating 1 resource(s)
[tiller] 2019/05/08 10:10:52 deleting crd-install hook servicemonitors.monitoring.coreos.com for release fuzzy-marsupial due to "before-hook-creation" policy
[kube] 2019/05/08 10:10:52 Starting delete for "servicemonitors.monitoring.coreos.com" CustomResourceDefinition
[kube] 2019/05/08 10:10:52 customresourcedefinitions.apiextensions.k8s.io "servicemonitors.monitoring.coreos.com" not found
[kube] 2019/05/08 10:10:52 building resources from manifest
[kube] 2019/05/08 10:10:52 creating 1 resource(s)
[tiller] 2019/05/08 10:10:52 hooks complete for crd-install fuzzy-marsupial
[tiller] 2019/05/08 10:10:53 executing 5 pre-install hooks for fuzzy-marsupial
[tiller] 2019/05/08 10:10:53 hooks complete for pre-install fuzzy-marsupial
[storage] 2019/05/08 10:10:53 getting release history for ""
[storage] 2019/05/08 10:10:53 creating release "fuzzy-marsupial.v1"
[kube] 2019/05/08 10:10:53 building resources from manifest
[kube] 2019/05/08 10:10:54 creating 109 resource(s)
[tiller] 2019/05/08 10:10:55 executing 5 post-install hooks for fuzzy-marsupial
[tiller] 2019/05/08 10:10:55 hooks complete for post-install fuzzy-marsupial
[storage] 2019/05/08 10:10:55 updating release "fuzzy-marsupial.v1"
[storage] 2019/05/08 10:10:56 getting last revision of "fuzzy-marsupial"
[storage] 2019/05/08 10:10:56 getting release history for "fuzzy-marsupial"
[kube] 2019/05/08 10:10:56 Doing get for PodSecurityPolicy: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: /PodSecurityPolicy/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for PodSecurityPolicy: "fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: /PodSecurityPolicy/fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for PodSecurityPolicy: "fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:56 get relation pod of object: /PodSecurityPolicy/fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:56 Doing get for PodSecurityPolicy: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:56 get relation pod of object: /PodSecurityPolicy/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:56 Doing get for PodSecurityPolicy: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:56 get relation pod of object: /PodSecurityPolicy/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:56 Doing get for PodSecurityPolicy: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:56 get relation pod of object: /PodSecurityPolicy/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:56 Doing get for Secret: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Secret/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for Secret: "alertmanager-fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Secret/alertmanager-fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-grafana-config-dashboards"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-grafana-config-dashboards
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-grafana-test"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-grafana-test
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-grafana-datasource"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-grafana-datasource
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-etcd"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-etcd
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-cluster-rsrc-use"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-cluster-rsrc-use
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-coredns"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-coredns
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-node-rsrc-use"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-node-rsrc-use
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-resources-cluster"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-resources-cluster
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-resources-namespace"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-resources-namespace
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-resources-pod"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-resources-pod
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-resources-workload"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-resources-workload
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-k8s-resources-workloads-namespace"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-k8s-resources-workloads-namespace
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-nodes"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-nodes
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-persistentvolumesusage"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-persistentvolumesusage
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-pods"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-pods
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-rook"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-rook
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-statefulset"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-statefulset
[kube] 2019/05/08 10:10:56 Doing get for ConfigMap: "fuzzy-marsupial-prometheus-traefik"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ConfigMap/fuzzy-marsupial-prometheus-traefik
[kube] 2019/05/08 10:10:56 Doing get for ServiceAccount: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ServiceAccount/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for ServiceAccount: "fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ServiceAccount/fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for ServiceAccount: "fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ServiceAccount/fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:56 Doing get for ServiceAccount: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ServiceAccount/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:56 Doing get for ServiceAccount: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ServiceAccount/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:56 Doing get for ServiceAccount: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/ServiceAccount/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-grafana-clusterrole"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-grafana-clusterrole
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "psp-fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/psp-fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "psp-fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/psp-fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-prometheus-operator-psp"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-prometheus-operator-psp
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:56 Doing get for ClusterRole: "fuzzy-marsupial-prometheus-prometheus-psp"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRole/fuzzy-marsupial-prometheus-prometheus-psp
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-grafana-clusterrolebinding"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-grafana-clusterrolebinding
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "psp-fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/psp-fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "psp-fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/psp-fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-prometheus-operator-psp"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-prometheus-operator-psp
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:56 Doing get for ClusterRoleBinding: "fuzzy-marsupial-prometheus-prometheus-psp"
[kube] 2019/05/08 10:10:56 get relation pod of object: /ClusterRoleBinding/fuzzy-marsupial-prometheus-prometheus-psp
[kube] 2019/05/08 10:10:56 Doing get for Role: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Role/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for Role: "fuzzy-marsupial-prometheus-prometheus-config"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Role/fuzzy-marsupial-prometheus-prometheus-config
[kube] 2019/05/08 10:10:56 Doing get for RoleBinding: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/RoleBinding/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for RoleBinding: "fuzzy-marsupial-prometheus-prometheus-config"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/RoleBinding/fuzzy-marsupial-prometheus-prometheus-config
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Service/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Service/fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Service/fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Service/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-coredns"
[kube] 2019/05/08 10:10:56 get relation pod of object: kube-system/Service/fuzzy-marsupial-prometheus-coredns
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-kube-controller-manager"
[kube] 2019/05/08 10:10:56 get relation pod of object: kube-system/Service/fuzzy-marsupial-prometheus-kube-controller-manager
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-kube-etcd"
[kube] 2019/05/08 10:10:56 get relation pod of object: kube-system/Service/fuzzy-marsupial-prometheus-kube-etcd
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-kube-scheduler"
[kube] 2019/05/08 10:10:56 get relation pod of object: kube-system/Service/fuzzy-marsupial-prometheus-kube-scheduler
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Service/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:56 Doing get for Service: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:56 get relation pod of object: default/Service/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:56 Doing get for DaemonSet: "fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/DaemonSet/fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:57 Doing get for Deployment: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Deployment/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:57 Doing get for Deployment: "fuzzy-marsupial-kube-state-metrics"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Deployment/fuzzy-marsupial-kube-state-metrics
[kube] 2019/05/08 10:10:57 Doing get for Deployment: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Deployment/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:57 Doing get for Ingress: "fuzzy-marsupial-grafana"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Ingress/fuzzy-marsupial-grafana
[kube] 2019/05/08 10:10:57 Doing get for Ingress: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Ingress/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:57 Doing get for Alertmanager: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Alertmanager/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:57 Doing get for Prometheus: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Prometheus/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-alertmanager.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-alertmanager.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-etcd"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-etcd
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-general.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-general.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-k8s.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-k8s.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kube-apiserver.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kube-apiserver.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kube-prometheus-node-alerting.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kube-prometheus-node-alerting.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kube-prometheus-node-recording.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kube-prometheus-node-recording.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kube-scheduler.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kube-scheduler.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kubernetes-absent"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kubernetes-absent
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kubernetes-apps"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kubernetes-apps
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kubernetes-resources"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kubernetes-resources
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kubernetes-storage"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kubernetes-storage
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-kubernetes-system"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-kubernetes-system
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-node-network"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-node-network
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-node-time"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-node-time
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-node.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-node.rules
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-prometheus-operator"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-prometheus-operator
[kube] 2019/05/08 10:10:57 Doing get for PrometheusRule: "fuzzy-marsupial-prometheus-prometheus.rules"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/PrometheusRule/fuzzy-marsupial-prometheus-prometheus.rules
[kube] 2019/05/08 10:10:57 Doing get for RoleBinding: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: kube-system/RoleBinding/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:57 Doing get for RoleBinding: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/RoleBinding/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:57 Doing get for Role: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: kube-system/Role/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:57 Doing get for Role: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/Role/fuzzy-marsupial-prometheus-prometheus
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-alertmanager"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-alertmanager
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-coredns"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-coredns
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-apiserver"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-apiserver
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-kube-controller-manager"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-kube-controller-manager
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-kube-etcd"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-kube-etcd
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-kube-scheduler"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-kube-scheduler
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-kube-state-metrics"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-kube-state-metrics
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-kubelet"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-kubelet
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-node-exporter"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-node-exporter
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-rook-ceph-mgr"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-rook-ceph-mgr
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-traefik"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-traefik
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-grafana"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-grafana
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-operator"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-operator
[kube] 2019/05/08 10:10:57 Doing get for ServiceMonitor: "fuzzy-marsupial-prometheus-prometheus"
[kube] 2019/05/08 10:10:57 get relation pod of object: default/ServiceMonitor/fuzzy-marsupial-prometheus-prometheus
```

### LINKED ISSUE #1026: Applications with RoleBindingList cause an error
If an application contains a list of resources and its kind is not `List` (e.g. `RoleBindingList`), Kubeapps won't identify it as a List with different items making the AppView crash. An example of application having this kind of resource is `prometheus-operator`.

See this related issue: https://github.com/kubeapps/kubeapps/issues/1025

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes #1026
Closes #1025

There are other type of lists apart than `List` (like `RoleBindingList`).

### CODE REVIEW

File: dashboard/src/components/AppView/AppView.tsx [hunk 1]
```diff
@@ -215,34 +215,38 @@ class AppView extends React.Component<IAppViewProps, IAppViewState> {
...
-            this.parseResources((i as IK8sList<IResource, {}>).items, releaseNamespace),
-            // Merge the list with the current result
-            (prev, newArray) => prev.concat(newArray),
-          );
-          break;
-        default:
-          result.otherResources.push(item);
+      // The item may be a list
+      const itemList = i as IK8sList<IResource, {}>;
+      if (itemList.items) {
```
Comment (prydonius) [inline dashboard/src/components/AppView/AppView.tsx]: I wonder if, to be safe, we should also check if `kind ~= /List/`?

Comment (andresmgot) [reply dashboard/src/components/AppView/AppView.tsx]: it seems more probably to me to find components that have an array of items and doesn't have `List` in the name (e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#downwardapivolumesource-v1-core)

Comment (prydonius) [reply dashboard/src/components/AppView/AppView.tsx]: The DownwardAPIVolumeSource isn't a top-level API resource, it's a type used in other resources. I'm fairly sure all Kubernetes core API resources use `List` in the name for list types. It is possible that a CRD can define a different name for list kinds (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#customresourcedefinitionnames-v1beta1-apiextensions-k8s-io), though note that the default is `<kind>List`.
