### PR TITLE
use two-step form for provisioning service instances

### LINKED ISSUE #362: [ServiceCatalog] Support $ref in JSON schema when creating service instances
I installed the GCP broker successfully and was able to browse the catalog, but when I tried to provision an instance of `Cloud SQL - MySQL` kubeapps only asked me for a `name` and then I got the following error:

```
Provision call failed: operation "projects/774136762833/operations/613f0c6f-6fd8-11e8-84d3-0a580a14020d/1528983987438762474" failed: generic::invalid_argument: Operation "operation-1528983987669-56e9a5373c808-85fbb4ea-f0547eb1" failed with : [{"code":"MANIFEST_EXPANSION_USER_ERROR","location":"/deployments/id2d9cfa0-1da6-49dc-a25a-02aed050eac4/manifests/manifest-1528983987754","message":"Manifest expansion encountered the following errors: Invalid properties for 'gcp-services/composite:cloud-sql-mysql-instance-f3622e2':\n'parameters' is a required property\n Resource: id2d9cfa0-1da6-49dc-a25a-02aed050eac4 Resource: config"}]
```

### PR DESCRIPTION
**Pull request by prydonius**
A two step form allows us to cleanly separate input that Kubeapps needs
from the generalised input from the Service Broker's schema. The first
form simply asks for the name of the Service Instance, and the second
form renders the parameters using the broker-provided instanceCreateParameterSchema.

fixes #362 

kubeapps svc cat paremeters 2-step

### CODE REVIEW

File: dashboard/src/components/ProvisionButton/index.tsx [hunk 1]
```diff
@@ -116,13 +120,23 @@ class ProvisionButton extends React.Component<IProvisionButtonProps, IProvisionB
     });
   };
 
+  public handleBackButton = (e: React.MouseEvent<HTMLButtonElement>) => {
+    e.preventDefault();
+    this.setState({ ...this.state, displayNameForm: true });
```
Comment (andresmgot) [inline dashboard/src/components/ProvisionButton/index.tsx]: do you need the `...this.state`?

File: dashboard/src/components/SchemaForm/FieldTemplate.tsx [hunk 2]
```diff
@@ -3,10 +3,15 @@ import { FieldTemplateProps } from "react-jsonschema-form";
...
 const FieldTemplate: React.SFC<FieldTemplateProps> = props => {
-  const { id, classNames, label, children, displayLabel } = props;
+  const { id, classNames, label, children, displayLabel, required } = props;
   return (
     <div className={classNames}>
-      {displayLabel && <label htmlFor={id}>{label}</label>}
+      {displayLabel && (
+        <label htmlFor={id}>
+          {label}
+          {required && " *"}
```
Comment (andresmgot) [inline dashboard/src/components/SchemaForm/FieldTemplate.tsx]: is quite obvious but a line at the end saying `* Mandatory fields` would be nice

File: dashboard/src/components/ProvisionButton/index.tsx (hunk 1 above)
Comment (prydonius) [reply dashboard/src/components/ProvisionButton/index.tsx]: oops no, thanks for catching that, I was debugging something and left that in!

File: dashboard/src/components/SchemaForm/FieldTemplate.tsx (hunk 2 above)
Comment (prydonius) [reply dashboard/src/components/SchemaForm/FieldTemplate.tsx]: What about changing it to `(required)`? I want to avoid adding an extra thing at the end of the form, the markup is already fairly messy.

If you're worried about users simply missing the required fields, the `required` html attribute is set so browsers should catch the error before forms are submitted.

**Comment by arapulido** [comment]
@prydonius Can we make the form that just asks for the name smaller, please?

File: dashboard/src/components/SchemaForm/FieldTemplate.tsx (hunk 2 above)
Comment (andresmgot) [reply dashboard/src/components/SchemaForm/FieldTemplate.tsx]: 👍 that's okay
