### PR TITLE
fix hardcoded references to kubeapps namespace in dashboard

### LINKED ISSUE #415: Fix hardcoded references to kubeapps namespace in Kubeapps UI
The Kubeapps UI references the `kubeapps` namespace in error alerts (e.g. https://github.com/kubeapps/kubeapps/pull/349#issuecomment-408122586 and https://github.com/kubeapps/kubeapps/pull/349#discussion_r205775026) but the Helm chart allows the chart to be installed in any namespace.

We should use the configuration to show the correct namespace in these error alerts.

### PR DESCRIPTION
**Pull request by prydonius**
also moves config into the redux store

fixes #415

### CODE REVIEW

File: dashboard/src/shared/App.ts [hunk 1]
```diff
@@ -19,11 +19,12 @@ export class App {
...
     releaseName: string,
     namespace: string,
+    kubeappsNamespace: string,
     chartVersion: IChartVersion,
     values?: string,
   ) {
     const chartAttrs = chartVersion.relationships.chart.data;
-    const repo = await AppRepository.get(chartAttrs.repo.name);
+    const repo = await AppRepository.get(chartAttrs.repo.name, kubeappsNamespace);
     const auth = repo.spec.auth;
```
Comment (migmartri) [inline dashboard/src/shared/App.ts]: Not from this patch but just pointing out inconsistent usage of es6 destructuring.

const { auth } = repo.spec;

File: dashboard/src/shared/AppRepository.ts [hunk 2]
```diff
@@ -1,30 +1,29 @@
 import { axios } from "./Auth";
-import Config from "./Config";
 import { IAppRepository, IAppRepositoryList } from "./types";
 
 export class AppRepository {
-  public static async list() {
-    const { data } = await axios.get<IAppRepositoryList>(await AppRepository.getResourceLink());
+  public static async list(namespace: string) {
```
Comment (migmartri) [inline dashboard/src/shared/AppRepository.ts]: is this namespace a kubeappsNamespace?

File: dashboard/src/shared/AppRepository.ts [hunk 3]
```diff
@@ -37,10 +36,12 @@ export class AppRepository {
 
   private static APIBase: string = "/api/kube";
   private static APIEndpoint: string = `${AppRepository.APIBase}/apis/kubeapps.com/v1alpha1`;
-  private static async getResourceLink(name?: string) {
-    const { namespace } = await Config.getConfig();
-    return `${AppRepository.APIEndpoint}/namespaces/${namespace}/apprepositories${
-      name ? `/${name}` : ""
-    }`;
+  private static getResourceLink(namespace?: string): string {
```
Comment (migmartri) [inline dashboard/src/shared/AppRepository.ts]: Could you please add a comment on why this URI resolution is needed?

File: dashboard/src/shared/App.ts [hunk 4]
```diff
@@ -19,11 +19,12 @@ export class App {
   public static async create(
     releaseName: string,
```
Comment (migmartri) [inline dashboard/src/shared/App.ts]: So this shared directory is like a shared set of `models`?

File: dashboard/src/shared/types.ts [hunk 5]
```diff
@@ -3,6 +3,7 @@ import { IServiceCatalogState } from "../reducers/catalog";
 import { IFunctionState } from "../reducers/functions";
 import { INamespaceState } from "../reducers/namespace";
 import { IAppRepositoryState } from "../reducers/repos";
+import { IConfig } from "./Config";
```
Comment (migmartri) [inline dashboard/src/shared/types.ts]: What's the reason for the I prefix?

File: dashboard/src/shared/Config.ts [hunk 6]
```diff
@@ -1,20 +1,15 @@
 import axios from "axios";
 
-interface IConfig {
+export interface IConfig {
```
Comment (migmartri) [inline dashboard/src/shared/Config.ts]: can you add a comment saying that this is the kubeapps configuration?

File: dashboard/src/shared/Config.ts [hunk 7]
```diff
@@ -1,20 +1,15 @@
...
   namespace: string;
 }
 
 export default class Config {
   public static async getConfig() {
-    if (Config.config) {
-      return Config.config;
-    }
     const url = `${Config.APIEndpoint}`;
```
Comment (migmartri) [inline dashboard/src/shared/Config.ts]: do you need the backticks?

File: dashboard/src/containers/Root.tsx [hunk 8]
```diff
@@ -14,6 +14,7 @@ import AppView from "./AppViewContainer";
 import ChartList from "./ChartListContainer";
 import ChartView from "./ChartViewContainer";
 import ClassListContainer from "./ClassListContainer";
+import { ClassViewContainer } from "./ClassView";
```
Comment (migmartri) [inline dashboard/src/containers/Root.tsx]: what for?

File: dashboard/src/reducers/config.ts [hunk 9]
```diff
@@ -0,0 +1,20 @@
+import { getType } from "typesafe-actions";
+
+import actions from "../actions";
+import { ConfigAction } from "../actions/config";
+import { IConfig } from "../shared/Config";
+
+const initialState: IConfig = {
+  namespace: "default",
```
Comment (migmartri) [inline dashboard/src/reducers/config.ts]: do we really want a default? I am wondering if this could have side-effects in the case that there are problems while retrieving the value from the config endpoint.

File: dashboard/src/shared/AppRepository.ts (hunk 2 above)
Comment (prydonius) [reply dashboard/src/shared/AppRepository.ts]: yes, but I don't AppRepository should really know about that, it just cares about what namespace to request from in the API

File: dashboard/src/reducers/config.ts (hunk 9 above)
Comment (prydonius) [reply dashboard/src/reducers/config.ts]: It's possible that there's a race condition here, yes. I need to look into this more.

File: dashboard/src/shared/App.ts (hunk 4 above)
Comment (prydonius) [reply dashboard/src/shared/App.ts]: Yes, correct. We try to keep all the API related methods here and not in the actual actions.

File: dashboard/src/shared/AppRepository.ts (hunk 3 above)
Comment (prydonius) [reply dashboard/src/shared/AppRepository.ts]: We're doing this in other classes so it's a common model and not something specific for this class

File: dashboard/src/shared/Config.ts (hunk 6 above)
Comment (prydonius) [reply dashboard/src/shared/Config.ts]: +1 will do

File: dashboard/src/shared/Config.ts (hunk 7 above)
Comment (prydonius) [reply dashboard/src/shared/Config.ts]: :+1: will fix

File: dashboard/src/shared/types.ts (hunk 5 above)
Comment (prydonius) [reply dashboard/src/shared/types.ts]: enforced by tslint https://palantir.github.io/tslint/rules/interface-name/

File: dashboard/src/shared/Config.ts [hunk 10]
```diff
@@ -1,20 +1,15 @@
...
     const { data } = await axios.get<IConfig>(url);
-    Config.config = data;
-    return Config.config;
+    return data;
   }
 
-  private static config: IConfig;
   private static APIEndpoint: string = "/config.json";
```
Comment (andresmgot) [inline dashboard/src/shared/Config.ts]: It's not related to this PR but this is a bit confusing (using `axios.get` with an "URL" to read a local file). Mostly because this action is now unnecessary async.

**Comment by prydonius** [comment]
> an alternative solution would be to add an env var in the dashboard container with the namespace of the pod

Hmm I'm not sure how we'd read the env var and respond with that from the nginx server, we could use an initContainer that creates the config.json file using that env var, but that might make it more difficult to add more configuration later. @migmartri what do you think?

File: dashboard/src/shared/Config.ts (hunk 10 above)
Comment (prydonius) [reply dashboard/src/shared/Config.ts]: @andresmgot perhaps you're misunderstanding this a bit? The nginx server serves the config.json file, it's not embedded in the React application. I'm not sure what you mean by local file, at some point the React app has to fetch this from the server.

File: dashboard/src/components/UpgradeForm/SelectRepoForm.tsx [hunk 11]
```diff
@@ -94,15 +88,24 @@ class SelectRepoForm extends React.Component<ISelectRepoFormProps, ISelectRepoFo
         case ForbiddenError:
           return (
             <PermissionsErrorAlert
-              namespace={RequiredRBACRoles.namespace || ""}
-              roles={[RequiredRBACRoles]}
-              action={`list app repositories`}
+              namespace={this.requiredRBACRoles().namespace || ""}
```
[the remark this answers is not in the document]
Comment (prydonius) [reply dashboard/src/components/UpgradeForm/SelectRepoForm.tsx]: :+1:

File: dashboard/src/shared/App.ts (hunk 1 above)
Comment (prydonius) [reply dashboard/src/shared/App.ts]: Should I fix this in this PR?

File: dashboard/src/shared/Config.ts (hunk 10 above)
Comment (migmartri) [reply dashboard/src/shared/Config.ts]: I think that the key here is that the React app is just a bundle of static files so AFAIK there is no way of exposing this env variable without triggering a build (via webpack) at deployment time.

If there was a way for Nginx to expose this env variable as a header that could be an alternative. Although I have not found any example nor insights on how to achieve so.

File: dashboard/src/reducers/config.ts (hunk 9 above)
Comment (prydonius) [reply dashboard/src/reducers/config.ts]: fixed, PTAL @migmartri

**Comment by prydonius** [comment]
@migmartri @andresmgot review addressed, PTAL!

File: dashboard/src/containers/Root.tsx [hunk 12]
```diff
@@ -52,20 +53,22 @@ class Root extends React.Component {
...
-              <PrivateRouteContainer
-                key={route}
-                exact={true}
-                path={route}
-                component={Root.exactRoutes[route]}
-              />
-            ))}
-          </Layout>
-        </ConnectedRouter>
+        <ConfigLoaderContainer>
```
Comment (migmartri) [inline dashboard/src/containers/Root.tsx]: Nice.

File: dashboard/src/reducers/config.ts [hunk 13]
```diff
@@ -0,0 +1,30 @@
...
+const initialState: IConfigState = {
+  loaded: false,
+  namespace: "",
+};
+
+const configReducer = (state: IConfigState = initialState, action: ConfigAction): IConfigState => {
+  switch (action.type) {
+    case getType(actions.config.requestConfig):
+      return initialState;
+    case getType(actions.config.receiveConfig):
```
Comment (migmartri) [inline dashboard/src/reducers/config.ts]: Minor comment. Shouldn't this be receivedConfig instead of receiveConfig? Just feels like `receiveConfig` is setting the intention instead of the result.

File: dashboard/src/reducers/config.ts [hunk 14]
```diff
@@ -0,0 +1,30 @@
...
+}
+
+const initialState: IConfigState = {
+  loaded: false,
+  namespace: "",
+};
+
+const configReducer = (state: IConfigState = initialState, action: ConfigAction): IConfigState => {
+  switch (action.type) {
+    case getType(actions.config.requestConfig):
```
Comment (migmartri) [inline dashboard/src/reducers/config.ts]: Not for this patch but in general we should start thinking of error handling so we do not run into cases like this one #433

File: dashboard/src/shared/App.ts (hunk 1 above)
Comment (migmartri) [reply dashboard/src/shared/App.ts]: No

File: dashboard/src/shared/AppRepository.ts (hunk 2 above)
Comment (migmartri) [reply dashboard/src/shared/AppRepository.ts]: Agreed, thanks for the explanation.

File: dashboard/src/shared/Config.ts (hunk 10 above)
Comment (prydonius) [reply dashboard/src/shared/Config.ts]: No problem, thanks for asking!
