### PR TITLE
Catch empty chart list

### LINKED ISSUE #470: Charts List view crashes if there are no charts
If you delete all the chart repos tracked in Kubeapps and then access the Charts page, you get a blank page and the app crashes.

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes #470

### CODE REVIEW

File: cmd/chartsvc/handler_test.go [hunk 1]
```diff
@@ -238,8 +239,11 @@ func Test_listCharts(t *testing.T) {
 			m.AssertExpectations(t)
 			assert.Equal(t, http.StatusOK, w.Code)
 
+			bb, _ := ioutil.ReadAll(w.Body)
```
Comment (migmartri) [inline cmd/chartsvc/handler_test.go]: What does bb mean? Can I suggest using more descriptive variable names? Thanks!

File: cmd/chartsvc/handler_test.go [hunk 2]
```diff
@@ -238,8 +239,11 @@ func Test_listCharts(t *testing.T) {
...
+			assert.NotEqual(t, string(bb), `{"data":null}`, "chart list shouldn't be null")
```
Comment (migmartri) [inline cmd/chartsvc/handler_test.go]: Is this test needed? Wouldn't be enough to check that it is an array of length len(tt.charts) as done below?

I am a confused though that the tests were previously passing. Is it because the assert.Len was comparing len(null) with 0?

Instead of blacklisting that case, we could check that it is an array before we check its length by for example using
https://godoc.org/github.com/stretchr/testify/assert#IsType

File: dashboard/src/components/ChartList/ChartList.tsx [hunk 3]
```diff
@@ -41,7 +41,7 @@ class ChartList extends React.Component<IChartListProps, IChartListState> {
   public render() {
     const { charts: { isFetching }, pushSearchFilter } = this.props;
     const items = this.filteredCharts(this.props.charts.items, this.state.filter);
-    if (!isFetching && !items) {
+    if (!isFetching && (!items || items.length === 0)) {
```
Comment (migmartri) [inline dashboard/src/components/ChartList/ChartList.tsx]: Is the !items required? items seems to be an array from the initial state https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/reducers/charts.ts#L9

File: cmd/chartsvc/handler_test.go (hunk 2 above)
Comment (andresmgot) [reply cmd/chartsvc/handler_test.go]: Indeed, found a better way to avoid that conversion (using a pointer).

File: cmd/chartsvc/handler_test.go [hunk 4]
```diff
@@ -240,12 +240,16 @@ func Test_listCharts(t *testing.T) {
 
 			var b bodyAPIListResponse
 			json.NewDecoder(w.Body).Decode(&b)
-			assert.Len(t, b.Data, len(tt.charts))
-			for i := range b.Data {
-				assert.Equal(t, b.Data[i].ID, tt.charts[i].ID, "chart id in the response should be the same")
-				assert.Equal(t, b.Data[i].Type, "chart", "response type is chart")
-				assert.Equal(t, b.Data[i].Links.(map[string]interface{})["self"], pathPrefix+"/charts/"+tt.charts[i].ID, "self link should be the same")
-				assert.Equal(t, b.Data[i].Relationships["latestChartVersion"].Data.(map[string]interface{})["version"], tt.charts[i].ChartVersions[0].Version, "latestChartVersion should match version at index 0")
+			if b.Data == nil {
```
Comment (migmartri) [inline cmd/chartsvc/handler_test.go]: This is great, thansk!
