### PR TITLE
Fix 'All Namespaces' button

### LINKED ISSUE #2289: Show apps in all namespace button keeps checked after changing the namespace
### Description:

Clicking in the button to show all namespace and then changing the namespace causes the toggle button to be active but the Kubeapps shows only the applications of the selected namespace.

Screenshot from 2021-01-28 12-26-41

Refreshing or clicking the button again solves the issue.

### Steps to reproduce the issue:

1. Click on "Show Apps in All Namespaces"
2. Change namespace in the context selector

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
2.1.0
```

### PR DESCRIPTION
**Pull request by andresmgot**
### Description of the change

Changing the namespace doesn't affect the `all namespaces` selection so the state should not be affected.

### Applicable issues

  - fixes #2289

### CODE REVIEW

File: dashboard/src/components/AppList/AppList.tsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ import "./AppList.css";
 import AppListGrid from "./AppListGrid";
 
 function AppList() {
-  const location = useLocation();
+  const location = ReactRouter.useLocation();
```
Comment (antgamdia) [inline dashboard/src/components/AppList/AppList.tsx:23]: Just out of curiosity: why this change?

**Review by antgamdia — APPROVED** [review]

File: dashboard/src/components/AppList/AppList.tsx (hunk 1 above)
Comment (andresmgot) [reply dashboard/src/components/AppList/AppList.tsx:23]: that's an interesting "gotcha". The problem is how `useLocation` is exported on it's package. It's directly exported as a function:

```
export function useLocation<S = H.LocationState>(): H.Location<S>;
```

but for mocking it as a spy, we are importing the whole `ReactRouter`: `jest.spyOn(ReactRouter, "useLocation")`. The problem is that if in the functional file, we only import the function (`import { useLocation } from react-router`) it won't use the mocked version of `ReactRouter` and  will import the real function. (testing things).

The thing is that this doesn't happen with other methods (like `useState` that I'm also using here) because it's exported as a method of a namespace:

```
declare namespace React {
...
    function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
```

so we will be always mocking the namespace, regardless how you import it. :)

Comment (antgamdia) [reply dashboard/src/components/AppList/AppList.tsx:23]: Ahhhh, got it. Thanks a lot for the explanation! It will be useful for my future tests :P
